
const keywordsArray = [
    "looking for freelancer",
    "freelance opportunities",
    "freelance work",
    "freelance jobs",
    "hire a freelancer",
    "freelancer for hire",
    "freelance developer",
    "freelance designer",
    "freelance writer",
    "freelance photographer",
    "freelance artist",
    "freelance graphic designer",
    "freelance web developer",
    "freelance software developer",
    "freelance app developer",
    "freelance digital marketer",
    "freelance SEO specialist",
    "freelance content writer",
    "freelance copywriter",
    "freelance editor",
    "freelance translator",
    "freelance illustrator",
    "freelance animator",
    "freelance video editor",
    "freelance motion designer",
    "freelance UI/UX designer",
    "freelance architect",
    "freelance interior designer",
    "freelance landscape designer",
    "freelance fashion designer",
    "freelance product designer",
    "freelance photographer for hire",
    "freelance event photographer",
    "freelance wedding photographer",
    "freelance portrait photographer",
    "freelance fashion photographer",
    "freelance food photographer",
    "freelance travel photographer",
    "freelance graphic designer for hire",
    "freelance logo designer",
    "freelance branding designer",
    "freelance web designer for hire",
    "freelance UX/UI designer",
    "freelance software developer for hire",
    "freelance app developer for hire",
    "freelance web developer for hire",
    "freelance digital marketer for hire",
    "freelance SEO specialist for hire",
    "freelance content writer for hire",
    "freelance copywriter for hire"
];

module.exports = keywordsArray;
